version: '3.3'
services:
 
  app:
    container_name: app-dev
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    links:
      - server

  app-test:
    container_name: app-test
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    environment:
      - CI=true
    command: npm test


  server:
    container_name: server-dev
    build: ./server
    ports:
      - 8080:8080

  server-test:
    container_name: server-test
    build: 
      context: ./server
      dockerfile: Dockerfile.test
    


  