# Use the production image as base image
FROM matias/node-test:latest
# Copy the test files
# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev

RUN npm install
# Override the command, to run the test instead of the application
CMD ["npm", "test"]